#! /bin/bash
sudo pkill uv4l
sudo pkill motion
sleep 10
uv4l -nopreview --video_nr 0 --driver raspicam --encoding mjpeg --width 640 --height 480 --framerate 20 --server-option '--port=8554' --server-option '--max-queued-connections=30' --server-option '--max-streams=25' --server-option '--max-threads=29'